package com.api.v1.doctors.enums;

public enum MedicalSpeciality {
    CARDIOLOGY,
    GASTROENTEROLOGY,
    OBSTETRICS_GYNAECOLOGY,
    PATHOLOGY,
    GERIATRIC_MEDICINE,
    OPHTHALMOLOGY,
    NEPHROLOGY,
    ANESTHESIOLOGY,
    EMERGENCY_MEDICINE,
    ONCOLOGY,
    ALLERGY_IMMUNOLOGY,
    PSYCHIATRY,
    HEMATOLOGY,
    FAMILY_MEDICINE,
    NEUROLOGY,
    CRITICAL_CARE_MEDICINE,
    DERMATOLOGY,
    SURGERY,
    CLINICAL_GENETICS,
    ENDOCRINOLOGY,
    INTERNAL_MEDICINE,
    HOSPICE_AND_PALLIATIVE_MEDICINE,
    PEDIATRICS,
    INFECTIOUS_DISEASE
}