package com.api.v1;

public enum MedicalSpecialization {

    CARDIOLOGY,
    NEUROLOGY,
    PEDIATRICS,
    DERMATOLOGY,
    ORTHOPEDICS,
    GASTROENTEROLOGY,
    ONCOLOGY,
    RADIOLOGY,
    PSYCHIATRY,
    ENDOCRINOLOGY,
    UROLOGY,
    OPHTHALMOLOGY,
    OBSTETRICS_AND_GYNECOLOGY,
    GENERAL_SURGERY,
    INTERNAL_MEDICINE
}
